[2024-07-22T11:09:23.089+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T11:09:23.107+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-07-22T11:09:21.231115+00:00 [queued]>
[2024-07-22T11:09:23.111+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-07-22T11:09:21.231115+00:00 [queued]>
[2024-07-22T11:09:23.112+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T11:09:23.120+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark_count_number_of_accidents> on 2024-07-22 11:09:21.231115+00:00
[2024-07-22T11:09:23.123+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=233) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T11:09:23.124+0000] {standard_task_runner.py:63} INFO - Started process 235 to run task
[2024-07-22T11:09:23.125+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'count_accidents', 'spark_count_number_of_accidents', 'manual__2024-07-22T11:09:21.231115+00:00', '--job-id', '1775', '--raw', '--subdir', 'DAGS_FOLDER/count_accidents.py', '--cfg-path', '/tmp/tmp75x45ppk']
[2024-07-22T11:09:23.126+0000] {standard_task_runner.py:91} INFO - Job 1775: Subtask spark_count_number_of_accidents
[2024-07-22T11:09:23.180+0000] {task_command.py:426} INFO - Running <TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-07-22T11:09:21.231115+00:00 [running]> on host dc154a8aeff9
[2024-07-22T11:09:23.250+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='count_accidents' AIRFLOW_CTX_TASK_ID='spark_count_number_of_accidents' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T11:09:21.231115+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T11:09:21.231115+00:00'
[2024-07-22T11:09:23.251+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T11:09:23.259+0000] {base.py:84} INFO - Using connection ID 'spark' for task execution.
[2024-07-22T11:09:23.260+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark:localhost:7077 --name arrow-spark --deploy-mode client /opt/airflow/spark/count_rows.py
[2024-07-22T11:09:23.305+0000] {spark_submit.py:571} INFO - /home/airflow/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-07-22T11:09:23.306+0000] {spark_submit.py:571} INFO - JAVA_HOME is not set
[2024-07-22T11:09:23.306+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T11:09:23.315+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark:localhost:7077 --name arrow-spark --deploy-mode client /opt/airflow/spark/count_rows.py. Error code is: 1.
[2024-07-22T11:09:23.318+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=count_accidents, task_id=spark_count_number_of_accidents, run_id=manual__2024-07-22T11:09:21.231115+00:00, execution_date=20240722T110921, start_date=20240722T110923, end_date=20240722T110923
[2024-07-22T11:09:23.325+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1775 for task spark_count_number_of_accidents (Cannot execute: spark-submit --master spark:localhost:7077 --name arrow-spark --deploy-mode client /opt/airflow/spark/count_rows.py. Error code is: 1.; 235)
[2024-07-22T11:09:23.347+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-22T11:09:23.362+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T11:09:23.363+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
