[2024-07-19T12:49:42.040+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T12:49:42.061+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-07-19T12:49:39.190418+00:00 [queued]>
[2024-07-19T12:49:42.067+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-07-19T12:49:39.190418+00:00 [queued]>
[2024-07-19T12:49:42.067+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-19T12:49:42.078+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark_count_number_of_accidents> on 2024-07-19 12:49:39.190418+00:00
[2024-07-19T12:49:42.083+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=139) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-19T12:49:42.084+0000] {standard_task_runner.py:63} INFO - Started process 141 to run task
[2024-07-19T12:49:42.085+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'count_accidents', 'spark_count_number_of_accidents', 'manual__2024-07-19T12:49:39.190418+00:00', '--job-id', '1638', '--raw', '--subdir', 'DAGS_FOLDER/count_accidents.py', '--cfg-path', '/tmp/tmp9k9z_5af']
[2024-07-19T12:49:42.087+0000] {standard_task_runner.py:91} INFO - Job 1638: Subtask spark_count_number_of_accidents
[2024-07-19T12:49:42.137+0000] {task_command.py:426} INFO - Running <TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-07-19T12:49:39.190418+00:00 [running]> on host a6434fe775f6
[2024-07-19T12:49:42.203+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='count_accidents' AIRFLOW_CTX_TASK_ID='spark_count_number_of_accidents' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T12:49:39.190418+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T12:49:39.190418+00:00'
[2024-07-19T12:49:42.204+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T12:49:42.212+0000] {base.py:84} INFO - Using connection ID 'spark' for task execution.
[2024-07-19T12:49:42.213+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 1g --driver-memory 1g --name arrow-spark --deploy-mode client ./spark/count_rows
[2024-07-19T12:49:42.284+0000] {spark_submit.py:571} INFO - /home/airflow/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-07-19T12:49:42.284+0000] {spark_submit.py:571} INFO - JAVA_HOME is not set
[2024-07-19T12:49:42.285+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T12:49:42.294+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 1g --driver-memory 1g --name arrow-spark --deploy-mode client ./spark/count_rows. Error code is: 1.
[2024-07-19T12:49:42.296+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=count_accidents, task_id=spark_count_number_of_accidents, run_id=manual__2024-07-19T12:49:39.190418+00:00, execution_date=20240719T124939, start_date=20240719T124942, end_date=20240719T124942
[2024-07-19T12:49:42.308+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1638 for task spark_count_number_of_accidents (Cannot execute: spark-submit --master spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 1g --driver-memory 1g --name arrow-spark --deploy-mode client ./spark/count_rows. Error code is: 1.; 141)
[2024-07-19T12:49:42.351+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-19T12:49:42.367+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T12:49:42.368+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
