[2024-07-22T11:12:44.766+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T11:12:44.787+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-07-22T11:12:42.866026+00:00 [queued]>
[2024-07-22T11:12:44.791+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-07-22T11:12:42.866026+00:00 [queued]>
[2024-07-22T11:12:44.791+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T11:12:44.798+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark_count_number_of_accidents> on 2024-07-22 11:12:42.866026+00:00
[2024-07-22T11:12:44.802+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=106) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T11:12:44.803+0000] {standard_task_runner.py:63} INFO - Started process 108 to run task
[2024-07-22T11:12:44.803+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'count_accidents', 'spark_count_number_of_accidents', 'manual__2024-07-22T11:12:42.866026+00:00', '--job-id', '1781', '--raw', '--subdir', 'DAGS_FOLDER/count_accidents.py', '--cfg-path', '/tmp/tmp05lkytd8']
[2024-07-22T11:12:44.805+0000] {standard_task_runner.py:91} INFO - Job 1781: Subtask spark_count_number_of_accidents
[2024-07-22T11:12:44.843+0000] {task_command.py:426} INFO - Running <TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-07-22T11:12:42.866026+00:00 [running]> on host 0deccaecadd1
[2024-07-22T11:12:44.909+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='count_accidents' AIRFLOW_CTX_TASK_ID='spark_count_number_of_accidents' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T11:12:42.866026+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T11:12:42.866026+00:00'
[2024-07-22T11:12:44.910+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T11:12:44.918+0000] {base.py:84} INFO - Using connection ID 'spark' for task execution.
[2024-07-22T11:12:44.918+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark:spark:7077 --name arrow-spark --deploy-mode client /opt/airflow/spark/count_rows.py
[2024-07-22T11:12:44.968+0000] {spark_submit.py:571} INFO - /home/airflow/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-07-22T11:12:44.969+0000] {spark_submit.py:571} INFO - JAVA_HOME is not set
[2024-07-22T11:12:44.969+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T11:12:44.978+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark:spark:7077 --name arrow-spark --deploy-mode client /opt/airflow/spark/count_rows.py. Error code is: 1.
[2024-07-22T11:12:44.981+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=count_accidents, task_id=spark_count_number_of_accidents, run_id=manual__2024-07-22T11:12:42.866026+00:00, execution_date=20240722T111242, start_date=20240722T111244, end_date=20240722T111244
[2024-07-22T11:12:44.993+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1781 for task spark_count_number_of_accidents (Cannot execute: spark-submit --master spark:spark:7077 --name arrow-spark --deploy-mode client /opt/airflow/spark/count_rows.py. Error code is: 1.; 108)
[2024-07-22T11:12:45.026+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-22T11:12:45.041+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T11:12:45.042+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
